.eslintrc.json, .gitignore, .storybook/main.ts, .storybook/preview.ts, package.json, src/components/commons/ButtonEx/ButtonEx.tsx, src/components/commons/ButtonEx/index.stories.tsx, src/stories/colors.mdx, yarn.lock
FE-50
yarn 해주세용!
사용시 내 컴포넌트 폴더에 컴포넌트명.stories.tsx 만들어서 사용하시고, 서버 시작 명령어는 yarn storybook 입니다.
=> ✨ FEATURE: storybook 설정

package.json, src/pages/register.tsx, src/store/useAuthStore.ts, yarn.lock
FE-71
/register 페이지에 데이터 입력 후 버튼을 누르면 POST 요청을 보냅니다.
습,,, 이슈를 너무 작게 쪼갠 것 같긴 한데 이미 쪼갰으니 빠른 리뷰를 위해 작은 크기로 push 합니다.
이어서 로그인 기능에서 토큰 저장과 회원가입 추가 구현, 로컬 스토리지에 유저 정보 저장 등 진행 될 예정입니다.
위의 사항들을 지금 진행하려니 로그인 기능이 필요하고 따로 이슈로 뺀 로그인 기능을 활용하기 위해서 ㅎ.. 짧게 올립니다.
=> ✨ FEATURE:  회원가입 시 서버에 POST 요청

src/components/commons/Label/index.tsx, src/pages/index.tsx
FE-67
Label 컴포넌트 만들었습니다.
-  "none" : h3 태그가 생성됩니다. "label" : input과 연결할 수 있는 일반 라벨입니다. "essential" : 필수값을 의미하는 *가 들어간 라벨입니다.
- type?: "none" | "label" | "essential"; 작성하지 않으면 기본적으로 none로 설정됩니다.
- content: string;
- htmlFor?: string;
- marginBottom?: 8 | 12 | 16; 라벨과 아래 요소 사이의 마진 값을 8, 12, 16으로 설정 가능합니다.
- center?: boolean; 라벨을 가운데로 정렬할 수 있습니다. 사용하면 true 사용하지 않으면 기본값(left)으로 처리됩니다.
- 기본적으로 display: block입니다. 옆에 다른 요소를 놓고 싶을 떄는 부모요소에 flex를 주고 margin bottom도 부모에서 한번에 처리해주세요.
스토리북 머지되기 전 마지막 피알이네요, Textarea부터는 스토리북으로 테스트 하겠습니다!
=> ✨ FEATURE: Label 컴포넌트 추가

src/components/commons/modal/OneInputModal.tsx, src/components/commons/modal/TwoInputModal.tsx
(FE-94)
props에 value랑 onChange 옵셔널로 추가했습니다 !
바로 머지하도록 하겠습니다
=> ♻️ REFACTOR: props에 onChange 추가 

package.json, src/pages/_app.tsx, yarn.lock
=> ⚙️ CHORE: tanstack 설치 및 적용 

package.json, src/components/commons/Button/index.tsx, src/components/commons/Spinner/Spinner.stories.tsx, src/components/commons/Spinner/index.tsx, yarn.lock
FE-96 
https://github.com/user-attachments/assets/31502f3d-082a-416d-86e2-bbab7ad9d33f
스피너 별로면 얘기해주세용!
=> ✨FEATURE: loading spinner

.env, src/components/auth/SendMailModal.tsx, src/hooks/auth/useLoginHandler.ts, src/hooks/auth/useRegisterHandler.ts, src/hooks/auth/useResetPasswordHandler.ts, src/middleware.ts, src/pages/oauth/[provider].tsx, src/pages/teams/index.tsx, src/store/useAuthStore.ts
FE-105
- 리다이렉트 버그 수정
- 로컬 스토리지 중첩 저장 수정
- api 함수 import 경로 수정
제가 미들웨어 설정을 바보같이 했네요 죄송합니다 ㅎ..
빠른 확인 부탁드려요
=> 🐛HOTFIX: 리다이렉트 버그 수정

src/components/board/ArticleDetail/CommentSection.tsx, src/pages/index.tsx
FE-88
onMutate를 이용해서 낙관적으로 댓글작성 완료 toast를 보내는데, 이걸 onSuccess로 바꾸는게 좋을까요?
아니면 옵티미스틱 UI를 적용해서 댓글 하나 미리 추가해주는게 나을까요 ?
=> ✨ FEATURE: comment section

src/api/taskApi.ts, src/components/task-list-page/DeleteModal.tsx, src/components/task-list-page/Task.tsx
FE-122
https://github.com/user-attachments/assets/aa33e487-3435-4a0a-9e08-ffa9089b30d8
ONCE로 생성한 일정은 삭제가 안되세요;;😬
=> ✨FEATURE: 할 일 삭제 모달 연결

public/icons/icon_toast_danger.svg, public/icons/icon_toast_info.svg, public/icons/icon_toast_success.svg, public/icons/icon_toast_warning.svg, src/components/commons/Toast/index.tsx, src/components/commons/modal/AddOrEditTaskListModal.tsx
FE-126
https://github.com/user-attachments/assets/7d139704-1b7c-40de-9d7a-055bf16b7e77
리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요  
ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=>  🎨 STYLE : toast 수정

src/components/task-list-page/Sidebar.tsx, src/components/task-list-page/Task.tsx, src/components/task-list-page/TaskList.tsx, src/components/task-list-page/sidebar/CommentInput.tsx, src/components/task-list-page/sidebar/index.tsx
=> ♻️ REFACTOR: 할일 상세보기 사이드바

src/hooks/useJoinTeam.ts
=> 🛠 FIX: useJoinTeam 버그 수정

@types/articleComment.ts, src/components/board/ArticleDetail/CommentSection.tsx, src/components/my-history/TaskHistory.tsx
FE-139
image가 string | null 형식이었는데 어디부분이랑 충돌이 나는진 몰라도 File 형식을 추가해야 되더라구요
근데 그렇게하면 다른 컴포넌트랑도 충돌이 일어나서 그냥 타입단언 시켰습니다
=> 🚀 DEPLOY: 빌드 에러 수정

@types/group.ts, src/components/Header/DesktopNavigation.tsx, src/components/auth/SendMailModal.tsx, src/components/board/ArticleDetail/CommentSection.tsx, src/components/commons/Input/ImageInput.tsx, src/components/commons/LottieAnimation/Loading.tsx, src/components/commons/NameTag/index.tsx, src/components/commons/Popover/index.tsx, src/components/edit-team/EditTeamForm.tsx, src/components/editUser/EditUserForm.tsx, src/components/teams/TeamItem.tsx, src/hooks/auth/useAuth.ts, src/hooks/useHeaderLogic.ts, src/hooks/useUpdateForm.ts, src/pages/_app.tsx, src/pages/oauth/[provider].tsx
FE-138
- 프로필, 팀 이미지 삭제 기능 추가
- user 데이터 요청 수정
밥먹고합시다~!
=> ♻️ REFACTOR: 이미지 삭제 기능, api 요청 수정

src/pages/login.tsx, src/pages/oauth/[provider].tsx
FE-143
환경변수 마지막에 슬래시 없는 걸로 가정하고 코드 수정했습니다
=> 🛠 FIX: added slash

src/hooks/useJoinTeam.ts
FE-148
팀 참여하기에 예외처리를 추가해서 
혹시 user가 유효하지 않을 때 에러메시지를 던지도록 처리했습니다.
=> ✨ FEATURE: useJoinTeam 경우의 수 추가

src/components/TeamDetailPage/TaskListItem.tsx, src/components/TeamDetailPage/TaskListSection.tsx, src/hooks/useTeamPageDnd.ts
FE-150
쿼리키가 맞지 않아서 생긴 버그여서 쿼리키를 최신화했습니다. (team -> group)
나머지는 api에 맡겨야 하네요..
팀 페이지의 할 일 목록 아이템의 라벨 색을 아이템마다의 고유한 값으로 매칭했습니다.
그 과정에서 prop 하나 이름을 더 적절하게 바꾼 것도 있습니다..!
=> 🛠 FIX: dnd 버그 수정, 스타일 체인지

src/components/commons/modal/OneInputModal.tsx, src/components/commons/modal/TwoInputModal.tsx, src/components/task-list-page/EditTaskModal.tsx, src/components/task-list-page/sidebar/index.tsx, src/pages/board/[boardId]/index.tsx, src/pages/board/index.tsx
=> ♻️ REFACTOR: Refactor

src/components/commons/NameTag/index.tsx, src/hooks/auth/useAuth.ts, src/hooks/auth/useResetPasswordHandler.ts, src/hooks/useUpdateForm.ts, src/pages/_app.tsx
FE-154
- 페이지 로딩 처리를 다시 시도해봅니다
- 로그인/로그아웃 트리거는 함수 내에 `router.push()` 추가로 해결합니다
- 혹시 몰라 트리거는 주석처리하고 테스트 후에 이상없으면 해당 코드는 제거하겠습니다.
- 네임택 ui를 조금 수정했습니다.
- 테스트 해보시고 혹시 이상 있으면 롤백하겠습니다!
=> ♻️ REFACTOR : 페이지 로딩 처리, 코드 정리

src/components/TeamDetailPage/TeamTitle.tsx, src/pages/_app.tsx
FE-156
팀 이름 부분 줄 바꿈 되게 했고, overFlow hidden 지워서 팝오버 잘 나타나게 했습니다.
로딩 로직의 의존성 배열 속 router를 뺐습니다. (정상작동합니다)
리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요  
ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> 🎨 STYLE: edited teamTitle (FE-156)

src/components/commons/Toast/index.tsx
=> 🎨 STYLE: toast 보더 제거

src/components/Header/UserPopoverMenu.tsx, src/components/TeamDetailPage/MemberCard.tsx, src/components/TeamDetailPage/MembersSection.tsx, src/components/TeamDetailPage/TaskListItem.tsx, src/components/TeamDetailPage/TaskListSection.tsx, src/components/TeamDetailPage/TeamPageModal.tsx, src/components/TeamDetailPage/TeamTitle.tsx, src/components/board/ArticleDetail/index.tsx, src/components/commons/Button/TextButton.tsx, src/components/commons/Popover/index.tsx, src/pages/teams/[teamId]/index.tsx
- FE-159
팀장 왕관 안보이는 버그 수정했습니다~!
제가 지금 반응형 255px 까지 처리해놨는데
페이지 마다 반응형이 조금 제각각이더라구요?
이거 한 번 통일하면 좋을 것 같아요
다른 분들 계획 없으시면 제가 해보겠습니다
=> 🛠 FIX: TeamPage 팀장 왕관 안보이는 버그 수정
